set-option global scrolloff 99,0 # keep the cursor in the center of the screen

colorscheme molokai

source ~/.config/kak/bepo.kak

define-command x write-quit

hook global WinSetOption filetype=rust %{
      set window formatcmd 'rustfmt'
}
